export const ma_txt_01_01:string = "극단 기억에 오신 것을 환영합니다."
export const ma_txt_03_01:string = "우리를 소개할게요"
export const ma_txt_03_02:string = "전체 보기"
export const ma_txt_04_01:string = "우리가 만든 기억이에요"
export const ma_txt_04_02:string = "전체 보기"
export const ma_txt_05_01:string = "기억이 궁금하시다면,"